sudo: required
language: cpp

env:
  global:
    - BOOST_LIBS="test,chrono,coroutine,program_options,random,regex,system,thread"
    - BOOST_PACKAGE="boost_1_66_0"
    - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.66.0/$BOOST_PACKAGE.tar.bz2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - CMAKE_URL="http://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz"

    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew update && brew upgrade cmake"
        - CMAKE_URL="http://cmake.org/files/v3.11/cmake-3.11.0-Darwin-x86_64.tar.gz"

before_install:
    - eval "${MATRIX_EVAL}"
    - |
      if [ ! -e $HOME/.local/$BOOST_PACKAGE/lib ]; then
        echo "CMake not found in the cache, get and extract it..."
        travis_retry curl -L ${BOOST_URL} \
          | tar -xz -C $HOME/.local --strip-components=1
        cd $HOME/.local/$BOOST_PACKAGE
        sudo ./bootstrap.sh --prefix=$HOME/.local/$BOOST_PACKAGE --with-libraries=$BOOST_LIBS
        ./b2 -d0
        sudo ./b2 install -d0
      else
        echo "Using cached Boost"
      fi
    - mkdir -p $HOME/.local
    - |
      if [ "$TRAVIS_OS_NAME" = "linux"  ]; then
        if [ ! -e $HOME/.local/bin/cmake ]; then
          echo "CMake not found in the cache, get and extract it..."
          travis_retry curl -L ${CMAKE_URL} \
            | tar -xz -C $HOME/.local --strip-components=1
        else
          echo "Using cached CMake"
        fi
      fi

compiler:
  - gcc

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake -DBOOST_ROOT:PATHNAME=$HOME/.local/$BOOST_PACKAGE ..

script:
  - ${CXX} --version
  - echo CXXFLAGS=${CXXFLAGS}
  - make